/* WALTER Build App data */
window.WALTER_DATA = {
  meta: {
    name: "WALTER",
    subtitle: "16″ closed-frame drum thickness sander",
    width: 16,
    drum: 5,
    rpm: 1089,
    sfm: 1427,
    envelope: "22 × 36 × 22″",
    budget: "$1,100–1,600",
    rev: "C",
  },
  parts: [
    { id: "frame", group: "frame", label: "Birch box + plates", detail: "Doubled ¾″ walls, ¼″ steel plates", color: "#c4a574" },
    { id: "drum", group: "drum", label: "5″ drum + shaft", detail: "21 discs, keyed ¾″ Stressproof", color: "#b4532a" },
    { id: "table", group: "table", label: "Platen + Acme", detail: "Torsion box, dual ¾-6, UHMW ways", color: "#e8eef0" },
    { id: "conveyor", group: "conveyor", label: "Crowned conveyor", detail: "2″ Al rollers, 16×60 PVC belt", color: "#2a2a2c" },
    { id: "motor", group: "motor", label: "1 HP drive", detail: "TEFC 56C, hinge + turnbuckle", color: "#161616" },
    { id: "hood", group: "hood", label: "Dust hood", detail: "¼″ birch, 4″ port, brush strip", color: "#3d4a46" },
    { id: "guard", group: "guard", label: "Belt guard", detail: "Fully enclosed ¼″ BB", color: "#8a6a42" },
    { id: "stand", group: "stand", label: "Cabinet (opt.)", detail: "32″ stand, shelf, mobile base", color: "#6e5638" },
  ],
  lumber: [
    { qty: 3, nom: "¾″ BB 5×5", len: "sheet", use: "Walls, base, discs, stretchers", bf: 0 },
    { qty: 1, nom: "¼″ BB 5×5", len: "sheet", use: "Hood, guard, platen skins", bf: 0 },
    { qty: 1, nom: "maple 8/4", len: "4′", use: "Base rails + nut blocks", bf: 5.3 },
  ],
  misc: [
    { item: "1 HP TEFC 1725 RPM 56C", qty: "1" },
    { item: "UCFL204-12 + UCFL201-10 bearings", qty: "2 + 4" },
    { item: "¾-6 Acme ×12″ + bronze nuts", qty: "2 + 2" },
    { item: "16×60 2-ply PVC conveyor belt", qty: "1" },
    { item: "4L440 link + 3.00/4.75 pulleys", qty: "1 set" },
    { item: "Magnetic starter, E-stop, 24 V PWM", qty: "1 set" },
  ],
  subsystems: [
    { id: "crown", name: "Crown + skew", where: "Conveyor rollers", lock: "0.030″ barrel, ¼-20 skew", tip: "The original sanding-belt-on-PVC never tracked. This is the whole trick." },
    { id: "acme", name: "Timed Acme", where: "Table elevation", lock: "HTD 5 mm or #25 chain", tip: "Two screws, one crank. Four independent screws will rack the platen." },
    { id: "jack", name: "Idle jack", where: "Left flange bearing", lock: "¼-20 ±0.040″", tip: "Walters used shim stock. Jack screws let you re-true without pulling the drum." },
    { id: "key", name: "Square key", where: "Shaft / discs", lock: "3/16″ × 4″", tip: "Not piano wire. Removable, kinder to the shaft." },
    { id: "novr", name: "No-volt release", where: "Drum motor", lock: "Magnetic starter", tip: "A blink of the lights must not restart the drum in your hands." },
    { id: "slots", name: "Paper retainers", where: "End bells", lock: "Slot + hook tape", tip: "Walters' Velcro was permanent. Slots let you change paper." },
  ],
  assembly: [
    { id: "a1", phase: "drum", title: "Cut and bore 21 discs", body: "Ø 5.125″ blanks, 0.748″ bore, 3/16″ keyway. Template T-DISC." },
    { id: "a2", phase: "drum", title: "Glue the stack on the keyed shaft", body: "0.5 mm gaps every 4 discs. End bells. True to 5.000″." },
    { id: "a3", phase: "frame", title: "Glue doubled walls", body: "Grain crossed, on a flat door. Steel plates as drill jigs. Idle wall slotted." },
    { id: "a4", phase: "frame", title: "Square the box", body: "Stretchers, base rails. Datum D1/D2. This is the machine's accuracy." },
    { id: "a5", phase: "table", title: "Torsion-box platen + ways", body: "UHMW dados, nut blocks, dual Acme, HTD sync, digital caliper, lock knobs." },
    { id: "a6", phase: "conveyor", title: "Turn crowns and track the belt", body: "0.030″ barrel. Endless PVC. Skew idle. Track empty, then loaded. Or skip — Option B slider." },
    { id: "a7", phase: "drive", title: "Hinge plate, motor, belt, guard", body: "Turnbuckle tension. 4L440. Full guard. Magnetic starter + E-stop." },
    { id: "a8", phase: "drive", title: "Hood, 4″ port, brush strip", body: "Foam to the walls. Collector on before any test cut." },
    { id: "a9", phase: "tune", title: "Wrap paper and true the drum", body: "W-13. Carrier board until the whole face cuts." },
    { id: "a10", phase: "tune", title: "Jack parallelism", body: "16″ test board kisses both ends. 0.010″ passes in poplar, then oak." },
    { id: "a11", phase: "tune", title: "Inspection Q01–Q10", body: "fab/12_QA/inspection.csv. E-stop blink test. No auto-restart." },
    { id: "a12", phase: "tune", title: "Post the startup card", body: "Collector → hood → lock → drum → feed. Never start with a board under the drum." },
  ],
  phases: [
    { id: "all", label: "All" },
    { id: "drum", label: "01 Drum" },
    { id: "frame", label: "02 Frame" },
    { id: "table", label: "03 Table" },
    { id: "conveyor", label: "04 Conveyor" },
    { id: "drive", label: "05 Drive" },
    { id: "tune", label: "06 Tune" },
  ],
  gallery: [
    { src: "../renders/walter_iso.svg", title: "Isometric", kind: "render" },
    { src: "../renders/walter_exploded.svg", title: "Exploded", kind: "render" },
    { src: "../renders/walter_cutaway.svg", title: "Cutaway", kind: "render" },
    { src: "../renders/walter_infeed.svg", title: "Infeed", kind: "render" },
    { src: "../renders/walter_drive.svg", title: "Drive side", kind: "render" },
    { src: "../renders/walter_top.svg", title: "Plan", kind: "render" },
    { src: "../renders/walter_stand.svg", title: "With stand", kind: "render" },
    { src: "../fab/06_DRAWINGS/G-001_cover.svg", title: "G-001 Cover", kind: "plan" },
    { src: "../fab/06_DRAWINGS/A-102_ortho.svg", title: "A-102 Ortho", kind: "plan" },
    { src: "../fab/06_DRAWINGS/E-101_exploded.svg", title: "E-101 Exploded", kind: "plan" },
    { src: "../fab/06_DRAWINGS/J-201_drum.svg", title: "J-201 Drum joint", kind: "plan" },
    { src: "../plans/W1_general.svg", title: "W-1 General", kind: "plan" },
    { src: "../plans/W2_frame.svg", title: "W-2 Frame", kind: "plan" },
    { src: "../plans/W3_drum.svg", title: "W-3 Drum", kind: "plan" },
    { src: "../plans/W4_elevation.svg", title: "W-4 Elevation", kind: "plan" },
    { src: "../plans/W5_conveyor.svg", title: "W-5 Conveyor", kind: "plan" },
    { src: "../plans/W6_drive.svg", title: "W-6 Drive", kind: "plan" },
    { src: "../plans/W7_dust_safety.svg", title: "W-7 Dust / safety", kind: "plan" },
    { src: "../plans/W8_bom.svg", title: "W-8 BOM", kind: "plan" },
    { src: "../plans/W9_exploded.svg", title: "W-9 Exploded", kind: "plan" },
    { src: "../plans/W10_templates.svg", title: "W-10 Templates", kind: "plan" },
    { src: "../plans/W11_stand.svg", title: "W-11 Stand", kind: "plan" },
    { src: "../plans/W12_wiring.svg", title: "W-12 Wiring", kind: "plan" },
    { src: "../plans/W13_wrap.svg", title: "W-13 Wrap", kind: "plan" },
    { src: "../plans/W14_buylist.svg", title: "W-14 Buy list", kind: "plan" },
  ],
  downloads: [
    { href: "../cad/walter_kernel.py", label: "walter_kernel.py", note: "Geometry kernel" },
    { href: "../cad/walter_sander.scad", label: "OpenSCAD", note: "Preview model" },
    { href: "../cad/walter_sander.py", label: "FreeCAD", note: "STEP when available" },
    { href: "../cad/exports/walter_assembly.stl", label: "assembly.stl", note: "3D mesh" },
    { href: "../cad/exports/walter_exploded.stl", label: "exploded.stl", note: "Exploded mesh" },
    { href: "../cad/exports/walter_stand.stl", label: "stand.stl", note: "With cabinet" },
    { href: "../cad/exports/walter_assembly.obj", label: "assembly.obj", note: "Wavefront" },
    { href: "../cad/parameters.json", label: "parameters.json", note: "Inches + derived" },
    { href: "../cad/parts.json", label: "parts.json", note: "Solid names" },
    { href: "../planforge/", label: "Planforge guidebook", note: "WOODWRIGHT v1.0" },
    { href: "../planforge/MCMASTER_SCHEDULE.csv", label: "McMaster CSV", note: "Verify live" },
    { href: "../fab/06_DRAWINGS/", label: "G/A/E/P/J drawings", note: "Rev C family" },
    { href: "../fab/07_BOM/master_bom.csv", label: "master_bom.csv", note: "Part register" },
    { href: "../fab/07_BOM/hardware.csv", label: "hardware.csv", note: "Buy list" },
    { href: "../fab/12_QA/fmea.csv", label: "fmea.csv", note: "Failure modes" },
    { href: "../", label: "Design page", note: "Overview" },
    { href: "../report/", label: "Engineering report", note: "Rev C" },
    { href: "../manual/", label: "LEGO build manual", note: "22 steps · 6 bags" },
    { href: "../guide/", label: "How to use", note: "Package map" },
  ],
  tools: [
    "Bandsaw + sanding drum / lathe for discs",
    "Drill press with fence (disc bores)",
    "Framing square, winding sticks",
    "Calipers + 16″ straightedge + feelers",
    "Welder or tap for Acme nut blocks (or buy nuts)",
    "4L pulley puller / link belt",
    "Multimeter (for the 24 V side)",
    "Dust collector 400+ CFM",
  ],
  rules: [
    "Collector on. Hood latched. Table locked. Then drum. Then feed.",
    "0.005–0.015″ per pass. If the motor note changes, you took too much.",
    "Nothing shorter than 12″ unless it is stuck to a carrier.",
    "This is not a planer.",
  ],
};
