/* MARTIN Build App — parametric design data (inches)
 * Rev C: mill-stock re-dimension (2×12 / 6×6 DF) + Japanese no-nail joinery.
 */
window.MARTIN_DATA = {
  meta: {
    name: "MARTIN",
    subtitle: "Prairie removable fence · Buffalo NY",
    length: 143,
    height: 65,
    gateClear: 36,
    bayClear: 46.5,
    dropDefault: 5,
    boardFeet: 322,
    boardFeetNote: "mill buy ≈322 bf · finished after re-dimension",
    paint: "Owner gray",
    climate: "Buffalo / Erie County NY",
    rev: "C",
    species: "Select Douglas fir + white oak hardware",
  },
  posts: [
    { id: "P0", name: "Latch post", x: 1.75, role: "Gate latch / house side" },
    { id: "P1", name: "Hinge post", x: 41.25, role: "Gate pintles" },
    { id: "P2", name: "Mid post", x: 91.25, role: "Cap scarf bearing" },
    { id: "P3", name: "End post", x: 141.25, role: "Run terminus" },
  ],
  rails: [
    { id: "R1", name: "Bottom Prairie band", cl: 10, stock: "1½×7¼ from 2×12 outer third" },
    { id: "R2", name: "Mid Prairie band", cl: 28, stock: "1½×7¼ from 2×12 outer third" },
    { id: "R3", name: "Upper Prairie band", cl: 46, stock: "1½×7¼ from 2×12 outer third" },
    { id: "CAP", name: "Weather cap", cl: 65, stock: "1½×7¼ from 2×12 · kama-tsugi" },
  ],
  parts: [
    { id: "pad", group: "base", label: "Leveling pad", detail: '155″ × 28″ × 6″ + drop makeup', color: "#9a9890" },
    { id: "piers", group: "base", label: "Socket piers (4)", detail: '14″ sq × 18″ tip-out · drained sleeves', color: "#b8b6b0" },
    { id: "posts", group: "frame", label: "Posts (4)", detail: 'Mill 6×6 → 3½×5½ · 65″ + 12″ tenon', color: "#d9dcde" },
    { id: "rails", group: "frame", label: "Nuki rails", detail: "From 2×12 VG outer thirds · wedge-locked", color: "#6e7578" },
    { id: "boards", group: "infill", label: "Privacy boards", detail: "From 1×12 → ¾×5½ VG · float · ¼″ gaps", color: "#cfd3d5" },
    { id: "cap", group: "frame", label: "Cap", detail: "Kama-tsugi scarf at P2 · oak peg", color: "#8a9094" },
    { id: "gate", group: "gate", label: "Gate leaf", detail: '36″ clear · drawbored hozo · no nails', color: "#e8eaeb" },
    { id: "latch", group: "gate", label: "Sliding latch bar", detail: "White oak into house sleeve or P0", color: "#aeb6ba" },
  ],
  lumber: [
    { qty: 4, nom: "6×6 DF Select", len: "8′", use: "Posts → mill 3½×5½×77″", bf: 96.0 },
    { qty: 5, nom: "2×12 DF Select", len: "12′", use: "Nuki R1–R3 + cap + gate frame", bf: 120.0 },
    { qty: 2, nom: "2×12 DF Select", len: "10′", use: "Gate / brace / spare cheeks", bf: 40.0 },
    { qty: 6, nom: "1×12 DF Select", len: "10′", use: "Privacy + gate boards → ¾×5½", bf: 60.0 },
    { qty: 1, nom: "8/4×6″ white oak", len: "6′", use: "Kusabi, pegs, pintles, latch", bf: 6.0 },
  ],
  finished: [
    { qty: "4", part: "Posts P0–P3", size: "3½×5½×77″", note: "Foot tenon 2½×4½×12″" },
    { qty: "3", part: "Nuki rails R1–R3", size: "1½×7¼×~105″", note: "Plow ⅜×⅞ · through P1–P3" },
    { qty: "2", part: "Cap scarf pair", size: "1½×7¼×~53″ ea", note: "Kama-tsugi at P2 + P0 stub" },
    { qty: "2", part: "Gate stiles", size: "1½×3½×~62″", note: "Hozo · wooden pintles" },
    { qty: "5", part: "Gate rails / brace", size: "1½×3½–5½×~29″", note: "Drawbore + half-lap" },
    { qty: "~40", part: "Boards", size: "¾×5½× course", note: "Float only — no fasteners" },
    { qty: "12+", part: "Kusabi", size: "⅝×1⅛×5½″", note: "White oak wedges" },
    { qty: "8+", part: "Pegs", size: "⌀⅜×~3″", note: "White oak drawbore" },
  ],
  misc: [
    { item: "Concrete 4000 psi air-entrained", qty: "~0.35 yd³" },
    { item: "#57 crushed stone", qty: "~0.4 yd³" },
    { item: "Sleeve liners (PVC Sch40 / galv.)", qty: "4" },
    { item: "End-grain sealer / wax (sticker period)", qty: "1" },
    { item: "Exterior primer + owner gray paint", qty: "1 kit" },
    { item: "Epoxy for house latch receiver (Latch A)", qty: "1" },
    { item: "Optional stainless pintles + padlock hasp", qty: "1 set" },
  ],
  joinery: [
    {
      id: "nuki",
      jp: "貫",
      name: "Nuki",
      where: "All Prairie rails through posts",
      lock: "Hardwood kusabi wedges",
      tip: "Rails from 2×12 outer thirds. Mortise = measured thickness × (7.25″ + 1/16″ ease). Zenwu walls. No nails.",
    },
    {
      id: "kusabi",
      jp: "楔",
      name: "Kusabi wedge",
      where: "Cheek slots beside each nuki",
      lock: "Friction — reverse to release",
      tip: "White oak ⅝″ × 1⅛″ × 5.5″. Bridge City kerf tools set angle. Never glue. Softwood wedges forbidden outdoors.",
    },
    {
      id: "hozo",
      jp: "ほぞ",
      name: "Hozo (M&T)",
      where: "Gate stile / rail frame",
      lock: "Drawbored oak peg",
      tip: "Bridge City tenon tooling + Temple saws + Zenwu. ⅛″ drawbore; ⌀⅜″ oak peg from MFT stop. No screws.",
    },
    {
      id: "kama",
      jp: "鎌継ぎ",
      name: "Kama-tsugi",
      where: "Cap scarf at P2",
      lock: "Drawbored peg",
      tip: "Universal V2 protractor for sickle angle. Shoot faces on Preda board. Oak peg only.",
    },
    {
      id: "groove",
      jp: "溝",
      name: "Floating groove",
      where: "Boards in rail edges",
      lock: "Cap retains — zero fasteners",
      tip: "⅜×⅞ plow on table saw (LS 36). Boards from 1×12 VG edge strips. ¼″ gaps for drainage/move.",
    },
    {
      id: "tenon",
      jp: "柄",
      name: "Foot tenon",
      where: "Post into pier sleeve",
      lock: "Gravity + optional oak cross-wedge",
      tip: "2½×4½×12 from milled 6×6 posts. Keep sleeve +¼″ for winter pull. Drain ⌀½″.",
    },
  ],
  assembly: [
    {
      id: "a0",
      phase: "mill",
      title: "Buy select mill stock",
      body: "Order M-6 list: 6×6 / 2×12 / 1×12 DF Select + 8/4 white oak. Reject pith-centered, twisted, or ring-shaken sticks on the lot.",
    },
    {
      id: "a0b",
      phase: "mill",
      title: "Sticker & acclimate",
      body: "Sticker 14+ days (¾″ stickers @ 12–16″, weight the top). Seal fresh ends. Parallel with pad pour if timing allows. See M-8.",
    },
    {
      id: "a1",
      phase: "base",
      title: "Measure opening & drop-off",
      body: "Confirm 143″ clear and driveway→garden drop with Incra rule / tape. Record in Drafts. Call 811 before digging.",
    },
    {
      id: "a2",
      phase: "base",
      title: "Compact gravel bed",
      body: "Place and compact #57 stone under the full pad footprint (pad + overhangs).",
    },
    {
      id: "a3",
      phase: "base",
      title: "Form & pour leveling pad",
      body: "Top of pad dead level. Makeup thickness = measured drop. Form four pier pockets or set precast piers.",
    },
    {
      id: "a4",
      phase: "base",
      title: "Install drained sleeves",
      body: "Set PVC/galv sleeves for 2.5×4.5 tenons + ¼″ clearance (winter pull). Drill ⌀½″ bottom drains. Cure concrete.",
    },
    {
      id: "a5",
      phase: "mill",
      title: "Re-dimension posts & rails",
      body: "TS + LS 36: 6×6 → 3½×5½ posts; 2×12 outer thirds → 1½×7¼ rails/cap; 1×12 edges → ¾×5½ boards. Plane reference faces. Track-saw posts to 77″.",
    },
    {
      id: "a6",
      phase: "timber",
      title: "Shoulder foot tenons",
      body: "Shoulder to 2½×4½×12 (LS 36 + Fence Guide). Plane cheeks (#5 / Bridge City). Dry-fit every sleeve.",
    },
    {
      id: "a7",
      phase: "timber",
      title: "Cut nuki mortises & wedge slots",
      body: "Story-stick CL at 10 / 28 / 46″. Bore waste; Zenwu + titanium hammer (+1/16″ height ease). Kerf-tool kusabi slots. No nails.",
    },
    {
      id: "a8",
      phase: "timber",
      title: "Plow board grooves",
      body: "⅜×⅞ on table saw — one locked LS 36 setup for all R1–R3. Cut board courses after dry-slide rails.",
    },
    {
      id: "a9",
      phase: "timber",
      title: "Dry-assemble privacy run",
      body: "Rails through P1–P3, drop boards, tap oak wedges snug. Cap kama-tsugi at P2 (protractor + Preda shoot), then drawbore oak peg.",
    },
    {
      id: "a10",
      phase: "gate",
      title: "Build gate leaf (hozo)",
      body: "Japanese M&T only — Bridge City tenon tooling, Temple saws, Zenwu cleanup. Half-lap brace. Drawbore from MFT stops. Wooden pintles on P1.",
    },
    {
      id: "a11",
      phase: "gate",
      title: "Install oak latch",
      body: "Latch A: oak bar into house concrete sleeve. Latch B: mortise in P0. Confirm swing. No screws in the leaf.",
    },
    {
      id: "a12",
      phase: "finish",
      title: "Paint",
      body: "Primer + two coats owner gray. Mask wedges, tenons, peg holes, sleeve contact, hinge faces.",
    },
    {
      id: "a13",
      phase: "finish",
      title: "Set & lock",
      body: "Drop posts into sleeves, re-insert rails/wedges, hang gate, engage latch. Plumb within ⅛″ over height.",
    },
  ],
  winter: [
    "Open gate · remove latch peg / padlock",
    "Knock out rail wedges — bag & label",
    "Slide nuki rails out (two-person)",
    "Lift boards out of grooves; bundle flat",
    "Lift gate leaf off pintles",
    "Lift each post straight up from sleeve",
    "Tip socket piers onto dolly; store dry",
    "Leave pad in place (or cover); mark sleeve holes",
  ],
  phases: [
    { id: "mill", label: "01 Mill" },
    { id: "base", label: "02 Base" },
    { id: "timber", label: "03 Timber" },
    { id: "gate", label: "04 Gate" },
    { id: "finish", label: "05 Finish" },
  ],
  gallery: [
    { src: "../renders/martin_iso.png", title: "Isometric", kind: "render" },
    { src: "../renders/martin_front.png", title: "Front elevation", kind: "render" },
    { src: "../renders/martin_gate.png", title: "Gate", kind: "render" },
    { src: "../renders/martin_pier.png", title: "Socket pier", kind: "render" },
    { src: "../renders/martin_below.png", title: "Below grade", kind: "render" },
    { src: "../plans/M1_general.svg", title: "M-1 General", kind: "plan" },
    { src: "../plans/M2_elevation.svg", title: "M-2 Elevation", kind: "plan" },
    { src: "../plans/M3_joinery.svg", title: "M-3 Joinery", kind: "plan" },
    { src: "../plans/M4_pad_piers.svg", title: "M-4 Pad & piers", kind: "plan" },
    { src: "../plans/M5_gate_latch.svg", title: "M-5 Gate", kind: "plan" },
    { src: "../plans/M6_cutlist.svg", title: "M-6 Mill BOM", kind: "plan" },
    { src: "../plans/M7_shop.svg", title: "M-7 Shop method", kind: "plan" },
    { src: "../plans/M8_mill.svg", title: "M-8 Grain & mill", kind: "plan" },
  ],
  downloads: [
    { href: "../cad/exports/martin.FCStd", label: "martin.FCStd", note: "FreeCAD model" },
    { href: "../cad/exports/martin_assembly.step", label: "STEP assembly", note: "CAD interchange" },
    { href: "../cad/exports/martin_timber.stl", label: "timber.stl", note: "3D mesh" },
    { href: "../cad/martin_fence.py", label: "martin_fence.py", note: "Parametric source" },
    { href: "../plans/M1_general.svg", label: "M-1 SVG", note: "Blueprint" },
    { href: "../plans/M6_cutlist.svg", label: "M-6 SVG", note: "Mill BOM" },
    { href: "../plans/M7_shop.svg", label: "M-7 SVG", note: "Shop method" },
    { href: "../plans/M8_mill.svg", label: "M-8 SVG", note: "Grain & mill" },
    { href: "../", label: "Design page", note: "Marketing overview" },
    { href: "../../report/", label: "Engineering report", note: "Full report" },
  ],
  tools: [
    "Festool track saw + MFT (Hongdui dogs / track hinge)",
    "Table saw + Festool TS LS 36 fence",
    "Woodpeckers Fence Guide V2",
    "Miter saw + Ryobi (rough crosscuts)",
    "Temple Tool rip + crosscut + flush trim saws",
    "Zenwu Y2 bench chisels + titanium hammer",
    "Stanley #5 + Bridge City bench plane",
    "Adrian Preda LW bench + shooting board",
    "Bridge City Universal V2 protractor",
    "Bridge City tenon tool + both kerf tools + Multi-Tool M1",
    "Incra 12″ rules + Kuratoga metal pencil",
    "Cordless drill + impact + Taylor countersink",
    "Clamps / bar clamps · stickers · paint kit",
  ],
  tolerances: [
    { item: "Layout", spec: "1/64″ on joinery faces · story-stick rail CL" },
    { item: "Nuki width", spec: "Measured rail thickness — sliding fit, no rattle" },
    { item: "Nuki height", spec: "7.25″ + 1/16″ seasonal ease only" },
    { item: "Foot tenon", spec: "2.5×4.5×12 · shoulders ±1/32″ · sleeve +¼″ clear" },
    { item: "Board plow", spec: "⅜″ deep × ⅞″ wide on TS (LS 36)" },
    { item: "Drawbore", spec: "⅛″ offset · ⌀⅜″ oak peg from MFT stop" },
    { item: "Moisture", spec: "Final mill after 14+ day sticker · reject movers" },
    { item: "Plumb", spec: "≤⅛″ over 65″ post height" },
  ],
  grainRules: [
    "Rip rails/cap from outer thirds of 2×12 — pith zone is waste",
    "Prefer vertical / rift grain on exposed faces and tenons",
    "Board strips from 1×12 edges with rings ~45–90° to face",
    "No nails, screws, plates, or glue on locking faces",
  ],
};
