/* MARTIN Build App — parametric design data (inches) */
window.MARTIN_DATA = {
  meta: {
    name: "MARTIN",
    subtitle: "Prairie removable fence · Buffalo NY",
    length: 143,
    height: 65,
    gateClear: 36,
    bayClear: 46.5,
    dropDefault: 0,
    boardFeet: 426,
    boardFeetNet: 371,
    paint: "Owner gray",
    climate: "Buffalo / Erie County NY",
    revision: "E",
  },
  posts: [
    { id: "P0", name: "Latch post", x: 1.75, role: "Gate latch / house side — no planter" },
    { id: "P1", name: "Hinge post", x: 41.25, role: "Oak pivots top + bottom" },
    { id: "P2", name: "Mid post", x: 91.25, role: "Cap scarf bearing" },
    { id: "P3", name: "End post", x: 141.25, role: "Run terminus" },
  ],
  rails: [
    { id: "KICK", name: "PT kick nuki", cl: 2.75, h: 5.5, stock: "2×6 PT", nuki: true },
    { id: "R-001", name: "S1 major nuki", cl: 10.125, h: 9.25, stock: "2×10", nuki: true },
    { id: "R-002", name: "S2 housed", cl: 18.25, h: 5.5, stock: "2×6", nuki: false },
    { id: "R-003", name: "S3 major / latch", cl: 26.375, h: 9.25, stock: "2×10", nuki: true },
    { id: "R-004", name: "S4 housed", cl: 34.5, h: 5.5, stock: "2×6", nuki: false },
    { id: "R-005", name: "S5 major nuki", cl: 42.625, h: 9.25, stock: "2×10", nuki: true },
    { id: "R-006", name: "S6 housed", cl: 50.75, h: 5.5, stock: "2×6", nuki: false },
    { id: "R-007", name: "S7 housed upper", cl: 58.875, h: 9.25, stock: "2×10", nuki: false },
    { id: "CAP", name: "Weather cap + light", cl: 65, h: 1.5, stock: "2×8 flat", nuki: false },
  ],
  parts: [
    { id: "sills", group: "base", label: "Dodai sills (2)", detail: "4×6 on edge · sit on driveway slab · no pour", color: "#9a9890" },
    { id: "ties", group: "base", label: "Cross-ties (4)", detail: "Post shoes · 3.5″ tenon drop-in", color: "#b8b6b0" },
    { id: "posts", group: "frame", label: "4×6 posts (4)", detail: "3.5×5.5 · 63.5″ body + 3.5″ tenon", color: "#d9dcde" },
    { id: "rails", group: "frame", label: "Prairie bands", detail: "2×10 / 2×6 · ¾″ dog gaps · nuki + housed dado", color: "#6e7578" },
    { id: "boards", group: "infill", label: "Tectonic blocks", detail: "2×2 chevrons · Darwin Martin pier texture", color: "#cfd3d5" },
    { id: "cap", group: "frame", label: "2×8 cap", detail: "Kama-tsugi at P2 · soffit light dado", color: "#8a9094" },
    { id: "gate", group: "gate", label: "Gate leaf", detail: "Flush to house · oak pivots · matching bands", color: "#e8eaeb" },
    { id: "latch", group: "gate", label: "Sliding latch bar", detail: "Oak into P0 mortise (Latch B default)", color: "#aeb6ba" },
  ],
  lumber: [
    { qty: 6, nom: "4×6", len: "8′", use: "Posts L-001…004 + F-003 ties", bf: 96.0 },
    { qty: 2, nom: "4×6", len: "16′", use: "Dodai sills F-001 / F-002", bf: 64.0 },
    { qty: 4, nom: "2×10", len: "10′", use: "Prairie bands R-001/003/005/007", bf: 66.7 },
    { qty: 1, nom: "2×8", len: "12′", use: "Cap C-001 + stub C-002", bf: 16.0 },
    { qty: 4, nom: "2×6", len: "10′", use: "Kick K-001 + housed 2×6 bands", bf: 40.0 },
    { qty: 9, nom: "2×6", len: "8′", use: "Gate + planters + braces", bf: 72.0 },
    { qty: 3, nom: "2×2", len: "8′", use: "Tectonic T-001 blocks", bf: 8.0 },
    { qty: 1, nom: "2×4", len: "8′", use: "Kusabi W-001 blanks", bf: 5.3 },
    { qty: 2, nom: "1×4 oak", len: "4′", use: "Pegs / latch / oak pivots", bf: 2.7 },
  ],
  misc: [
    { item: "Rubber furniture pads (driveway sill)", qty: "8" },
    { item: "Live planter mix + optional in-box drainage stone (2 troughs)", qty: "see ballast" },
    { item: "12V IP65 LED tape + driver (cap soffit)", qty: "1 kit" },
    { item: "Exterior primer + owner gray paint", qty: "1 kit" },
    { item: "Optional stainless pintles + padlock hasp", qty: "1 set" },
  ],
  joinery: [
    { id: "nuki", jp: "貫", name: "Nuki", where: "K-001 + R-001/003/005 through posts", lock: "Hardwood kusabi wedges", tip: "Through-mortise only these four. Cheeks 2″ each side of the 1.5″ slat." },
    { id: "housed", jp: "溝", name: "Housed dado", where: "R-002/004/006/007", lock: "0.75″ housing — keep the post web", tip: "Do not through-mortise all seven bands. ¾″ gaps would leave a ¾″ web." },
    { id: "kusabi", jp: "楔", name: "Kusabi wedge", where: "Cheek slots beside each nuki", lock: "Friction — reverse to release", tip: "⅝″ × 1⅛″ × 5.5″ hardwood. Never glue." },
    { id: "hozo", jp: "ほぞ", name: "Hozo (M&T)", where: "Gate stile / rail frame", lock: "Drawbored oak peg", tip: "⅛″ drawbore offset pulls joint closed." },
    { id: "kama", jp: "鎌継ぎ", name: "Kama-tsugi", where: "Cap scarf at P2", lock: "Drawbored peg", tip: "Sickle scarf in 2×8. Light dado on the soffit." },
    { id: "pivot", jp: "枢", name: "Oak pivot", where: "Sill + cap at P1", lock: "Locational / lift-off +Z", tip: "⌀1.25″. Leaf weight into the driveway sill — not a pintle off P0." },
    { id: "tenon", jp: "柄", name: "Foot tenon", where: "Post into F-003 cross-tie", lock: "Gravity drop-in", tip: "2.5″ × 4.5″ × 3.5″. Lift out for winter. No sleeve." },
  ],
  assembly: [
    { id: "a1", phase: "base", title: "Measure opening on the driveway", body: "Confirm 143″ clear from existing fence to house siding. Gate will sit against the house. Do not dig. Do not pour." },
    { id: "a2", phase: "base", title: "Place rubber pads", body: "Set H-001 pads on the driveway where the sill will sit. Protect pavement — no fasteners into the drive." },
    { id: "a3", phase: "base", title: "Build the timber ladder", body: "Half-lap F-001/F-002 sills to four F-003 cross-ties. Peg. Sit the frame on the slab. Pack F-004 only if outriggers leave the concrete." },
    { id: "a4", phase: "base", title: "Build two live planters", body: "F-005 troughs on the garden side of bays P1–P2 and P2–P3 only. No planter at the house/gate. Drainage slots; ½″ air gap from posts." },
    { id: "a5", phase: "timber", title: "Cut posts & shoulder tenons", body: "Four 4×6 blanks → 67.00″ (63.50″ body + 3.50″ tenon). Shoulder to 2.5×4.5. Dry-fit F-003." },
    { id: "a6", phase: "timber", title: "Cut nuki mortises, housed dados, wedge slots", body: "Through-mortise K-001 + R-001/003/005. House R-002/004/006/007 0.75″. Cut kusabi cheek slots. Oak pivot sockets at P1." },
    { id: "a7", phase: "timber", title: "Mill Prairie bands", body: "2×10 and 2×6 to nuki_len 104.50″. PT kick. Ease 1/16″. Do not rip 2×10 to force φ." },
    { id: "a8", phase: "timber", title: "Dry-assemble privacy run", body: "Bands through P1–P3, tap wedges, ¾″ gap gauge. Cap with kama-tsugi at P2, drawbore. Tectonic chevrons." },
    { id: "a9", phase: "gate", title: "Build gate leaf", body: "Drawbored hozo joints, half-lap brace, horizontal infill matching the screen. Fit oak pivots W-003 — bottom in sill, top in cap." },
    { id: "a10", phase: "gate", title: "Install latch", body: "Latch B default: oak bar into mortise in P0. Confirm swing arc. No epoxy into the house. No planter at P0." },
    { id: "a11", phase: "finish", title: "Paint for Buffalo", body: "Ease arrises, end-grain sealer, PT dry then prime, two owner-gray coats, extra on planter interiors. Mask joinery faces." },
    { id: "a12", phase: "finish", title: "Set, plant, light", body: "Drop posts into F-003, re-insert bands/wedges, hang gate, plant troughs + optional in-box stone, install IP65 tape (driver in P3 planter)." },
  ],
  winter: [
    "Open gate · remove latch peg / padlock",
    "Knock out rail wedges — bag & label",
    "Slide nuki bands out (two-person)",
    "Withdraw housed slats toward P3",
    "Lift gate leaf off oak pivots",
    "Lift each post straight up from F-003",
    "Empty planters (or lift troughs); store dry",
    "Carry the timber ladder indoors or leave sills — nothing is buried",
  ],
  phases: [
    { id: "base", label: "01 Base" },
    { id: "timber", label: "02 Timber" },
    { id: "gate", label: "03 Gate" },
    { id: "finish", label: "04 Finish" },
  ],
  gallery: [
    { src: "../renders/martin_iso.png", title: "Isometric", kind: "render" },
    { src: "../renders/martin_front.png", title: "Front elevation", kind: "render" },
    { src: "../renders/martin_gate.png", title: "Gate", kind: "render" },
    { src: "../plans/M1_general.svg", title: "M-1 General", kind: "plan" },
    { src: "../plans/M2_elevation.svg", title: "M-2 Elevation", kind: "plan" },
    { src: "../plans/M3_joinery.svg", title: "M-3 Joinery", kind: "plan" },
    { src: "../plans/M4_pad_piers.svg", title: "M-4 Ladder base", kind: "plan" },
    { src: "../plans/M5_gate_latch.svg", title: "M-5 Gate", kind: "plan" },
    { src: "../plans/M6_cutlist.svg", title: "M-6 Cut list", kind: "plan" },
  ],
  downloads: [
    { href: "../fab/", label: "Fabrication package", note: "BOM, drawings, QA, JSON" },
    { href: "../fab/00_SOURCE/martin_project.json", label: "martin_project.json", note: "Machine-readable source" },
    { href: "../cad/exports/martin.FCStd", label: "martin.FCStd", note: "FreeCAD model" },
    { href: "../cad/exports/martin_assembly.step", label: "STEP assembly", note: "CAD interchange" },
    { href: "../cad/exports/martin_timber.stl", label: "timber.stl", note: "3D mesh" },
    { href: "../cad/martin_fence.py", label: "martin_fence.py", note: "Parametric source" },
    { href: "../plans/M1_general.svg", label: "M-1 SVG", note: "Blueprint" },
    { href: "../plans/M6_cutlist.svg", label: "M-6 SVG", note: "Cut list" },
    { href: "../", label: "Design page", note: "Marketing overview" },
    { href: "../../report/", label: "Engineering report", note: "Rev E" },
  ],
  tools: [
    "Track saw, miter saw, table saw",
    "Hand planes + Japanese saws",
    "Bridge City kerf / tenon makers",
    "Zenwu pairing chisels",
    "Layout tools (gauge, knife, square)",
    "⅜″ brad point (drawbore)",
    "Level + string line",
    "Paint brushes / sprayer",
  ],
};
