/* MARTIN Build App — parametric design data (inches)
 * Rev B: tolerances & sequence mapped to owner Festool / Bridge City / Zenwu kit.
 */
window.MARTIN_DATA = {
  meta: {
    name: "MARTIN",
    subtitle: "Prairie removable fence · Buffalo NY",
    length: 143,
    height: 65,
    gateClear: 36,
    bayClear: 46.5,
    dropDefault: 5,
    boardFeet: 303,
    paint: "Owner gray",
    climate: "Buffalo / Erie County NY",
    rev: "B",
  },
  posts: [
    { id: "P0", name: "Latch post", x: 1.75, role: "Gate latch / house side" },
    { id: "P1", name: "Hinge post", x: 41.25, role: "Gate pintles" },
    { id: "P2", name: "Mid post", x: 91.25, role: "Cap scarf bearing" },
    { id: "P3", name: "End post", x: 141.25, role: "Run terminus" },
  ],
  rails: [
    { id: "R1", name: "Bottom Prairie band", cl: 10, stock: "2×8 on edge" },
    { id: "R2", name: "Mid Prairie band", cl: 28, stock: "2×8 on edge" },
    { id: "R3", name: "Upper Prairie band", cl: 46, stock: "2×8 on edge" },
    { id: "CAP", name: "Weather cap", cl: 65, stock: "2×8 flat" },
  ],
  parts: [
    { id: "pad", group: "base", label: "Leveling pad", detail: '155″ × 28″ × 6″ + drop makeup', color: "#9a9890" },
    { id: "piers", group: "base", label: "Socket piers (4)", detail: '14″ sq × 18″ tip-out · drained sleeves', color: "#b8b6b0" },
    { id: "posts", group: "frame", label: "4×6 posts (4)", detail: '3.5×5.5 · 65″ + 12″ foot tenon', color: "#d9dcde" },
    { id: "rails", group: "frame", label: "2×8 nuki rails", detail: "R1–R3 through-posts, wedge-locked", color: "#6e7578" },
    { id: "boards", group: "infill", label: "1×6 privacy boards", detail: "¾″ float in rail grooves · ¼″ gaps", color: "#cfd3d5" },
    { id: "cap", group: "frame", label: "2×8 cap", detail: "Kama-tsugi scarf at P2", color: "#8a9094" },
    { id: "gate", group: "gate", label: "Gate leaf", detail: '36″ clear · drawbored M&T · brace', color: "#e8eaeb" },
    { id: "latch", group: "gate", label: "Sliding latch bar", detail: "Oak into house sleeve or P0", color: "#aeb6ba" },
  ],
  lumber: [
    { qty: 4, nom: "4×6", len: "8′", use: "Posts P0–P3", bf: 64.0 },
    { qty: 6, nom: "2×8", len: "10′", use: "Prairie nuki rails R1–R3", bf: 80.0 },
    { qty: 3, nom: "2×8", len: "12′", use: "Cap + latch bar stock", bf: 48.0 },
    { qty: 4, nom: "2×6", len: "8′", use: "Gate stiles / rails", bf: 32.0 },
    { qty: 18, nom: "1×6", len: "8′", use: "Privacy + gate boards (¾″)", bf: 72.0 },
    { qty: 1, nom: "2×4", len: "8′", use: "Wedge (kusabi) blanks", bf: 5.3 },
    { qty: 1, nom: "1×4 oak", len: "4′", use: "Pegs + pintle blanks", bf: 1.3 },
  ],
  misc: [
    { item: "Concrete 4000 psi air-entrained", qty: "~0.35 yd³" },
    { item: "#57 crushed stone", qty: "~0.4 yd³" },
    { item: "Sleeve liners (PVC Sch40 / galv.)", qty: "4" },
    { item: "Exterior primer + owner gray paint", qty: "1 kit" },
    { item: "Epoxy for house latch receiver (Latch A)", qty: "1" },
    { item: "Optional stainless pintles + padlock hasp", qty: "1 set" },
  ],
  joinery: [
    {
      id: "nuki",
      jp: "貫",
      name: "Nuki",
      where: "All Prairie rails through posts",
      lock: "Hardwood kusabi wedges",
      tip: "Mortise = measured rail thickness (≈1.5″) × (7.25″ + 1/16″ ease). Bore waste, Zenwu walls, Temple/flush trim exits. Sliding fit — plane rail cheeks if proud.",
    },
    {
      id: "kusabi",
      jp: "楔",
      name: "Kusabi wedge",
      where: "Cheek slots beside each nuki",
      lock: "Friction — reverse to release",
      tip: "⅝″ × 1⅛″ × 5.5″ hardwood. Bridge City kerf tools set angle; rip on TS; hand-fit each slot. Never glue.",
    },
    {
      id: "hozo",
      jp: "ほぞ",
      name: "Hozo (M&T)",
      where: "Gate stile / rail frame",
      lock: "Drawbored oak peg",
      tip: "Bridge City tenon tooling + Temple saws + Zenwu cleanup. ⅛″ drawbore offset; brad-point from MFT stop; ⅜″ oak peg.",
    },
    {
      id: "kama",
      jp: "鎌継ぎ",
      name: "Kama-tsugi",
      where: "Cap scarf at P2",
      lock: "Drawbored peg",
      tip: "Universal V2 protractor for sickle angle. Shoot mating faces on Preda board before pegging.",
    },
    {
      id: "groove",
      jp: "溝",
      name: "Floating groove",
      where: "1×6 boards in rail edges",
      lock: "Cap retains",
      tip: "⅜″ deep × ⅞″ wide plow on table saw with LS 36 (no router). ¼″ board gaps. One fence setup for all rails.",
    },
    {
      id: "tenon",
      jp: "柄",
      name: "Foot tenon",
      where: "Post into pier sleeve",
      lock: "Gravity + optional cross-wedge",
      tip: "2.5″ × 4.5″ × 12″. TS shoulders (±1/32″) · plane cheeks. Keep sleeve +¼″ clearance for winter pull. Drain ⌀½″.",
    },
  ],
  assembly: [
    {
      id: "a1",
      phase: "base",
      title: "Measure opening & drop-off",
      body: "Confirm 143″ clear and driveway→garden drop with Incra rule / tape. Record in Drafts. Call 811 before digging.",
    },
    {
      id: "a2",
      phase: "base",
      title: "Compact gravel bed",
      body: "Place and compact #57 stone under the full pad footprint (pad + overhangs).",
    },
    {
      id: "a3",
      phase: "base",
      title: "Form & pour leveling pad",
      body: "Top of pad dead level. Makeup thickness = measured drop. Form four pier pockets or set precast piers.",
    },
    {
      id: "a4",
      phase: "base",
      title: "Install drained sleeves",
      body: "Set PVC/galv sleeves for 2.5×4.5 tenons + ¼″ clearance (keep — winter pull). Drill ⌀½″ bottom drains. Cure concrete.",
    },
    {
      id: "a5",
      phase: "timber",
      title: "Cut posts & shoulder tenons",
      body: "Dog 4×6 on MFT; Festool track saw to 77″. TS + LS 36 (+ Woodpeckers Fence Guide) shoulders to 2.5×4.5. Plane cheeks (#5 / Bridge City); dry-fit every sleeve.",
    },
    {
      id: "a6",
      phase: "timber",
      title: "Cut nuki mortises & wedge slots",
      body: "Story-stick CL at 10 / 28 / 46″ (M1 + Incra + Kuratoga). Bore waste; Zenwu + titanium hammer to walls (+1/16″ height ease). Kerf tools → kusabi cheek slots.",
    },
    {
      id: "a7",
      phase: "timber",
      title: "Mill rails & board grooves",
      body: "2×8 rails on edge. Plow ⅜×⅞ grooves on the table saw with LS 36 — one locked setup for all. Cut boards to course heights (track saw / miter).",
    },
    {
      id: "a8",
      phase: "timber",
      title: "Dry-assemble privacy run",
      body: "Rails through P1–P3, drop boards into grooves, tap wedges snug. Cap with kama-tsugi at P2 (protractor + Preda shoot), then drawbore.",
    },
    {
      id: "a9",
      phase: "gate",
      title: "Build gate leaf",
      body: "Hozo with Bridge City tenon + Temple saws; half-lap brace (protractor + shoot). Drawbore from MFT stops. Fit wooden pintles on P1.",
    },
    {
      id: "a10",
      phase: "gate",
      title: "Install latch",
      body: "Latch A: oak bar into house concrete sleeve. Latch B: mortise in P0. Confirm swing arc. Optional Taylor countersink on peg faces only.",
    },
    {
      id: "a11",
      phase: "finish",
      title: "Paint",
      body: "Primer + two coats owner gray. Mask wedges, tenons, sleeve contact, and hinge faces.",
    },
    {
      id: "a12",
      phase: "finish",
      title: "Set & lock",
      body: "Drop posts into sleeves, re-insert rails/wedges, hang gate, engage latch. Walk for plumb within ⅛″ over height.",
    },
  ],
  winter: [
    "Open gate · remove latch peg / padlock",
    "Knock out rail wedges — bag & label",
    "Slide nuki rails out (two-person)",
    "Lift boards out of grooves; bundle flat",
    "Lift gate leaf off pintles",
    "Lift each post straight up from sleeve",
    "Tip socket piers onto dolly; store dry",
    "Leave pad in place (or cover); mark sleeve holes",
  ],
  phases: [
    { id: "base", label: "01 Base" },
    { id: "timber", label: "02 Timber" },
    { id: "gate", label: "03 Gate" },
    { id: "finish", label: "04 Finish" },
  ],
  gallery: [
    { src: "../renders/martin_iso.png", title: "Isometric", kind: "render" },
    { src: "../renders/martin_front.png", title: "Front elevation", kind: "render" },
    { src: "../renders/martin_gate.png", title: "Gate", kind: "render" },
    { src: "../renders/martin_pier.png", title: "Socket pier", kind: "render" },
    { src: "../renders/martin_below.png", title: "Below grade", kind: "render" },
    { src: "../plans/M1_general.svg", title: "M-1 General", kind: "plan" },
    { src: "../plans/M2_elevation.svg", title: "M-2 Elevation", kind: "plan" },
    { src: "../plans/M3_joinery.svg", title: "M-3 Joinery", kind: "plan" },
    { src: "../plans/M4_pad_piers.svg", title: "M-4 Pad & piers", kind: "plan" },
    { src: "../plans/M5_gate_latch.svg", title: "M-5 Gate", kind: "plan" },
    { src: "../plans/M6_cutlist.svg", title: "M-6 Cut list", kind: "plan" },
    { src: "../plans/M7_shop.svg", title: "M-7 Shop method", kind: "plan" },
  ],
  downloads: [
    { href: "../cad/exports/martin.FCStd", label: "martin.FCStd", note: "FreeCAD model" },
    { href: "../cad/exports/martin_assembly.step", label: "STEP assembly", note: "CAD interchange" },
    { href: "../cad/exports/martin_timber.stl", label: "timber.stl", note: "3D mesh" },
    { href: "../cad/martin_fence.py", label: "martin_fence.py", note: "Parametric source" },
    { href: "../plans/M1_general.svg", label: "M-1 SVG", note: "Blueprint" },
    { href: "../plans/M6_cutlist.svg", label: "M-6 SVG", note: "Cut list" },
    { href: "../plans/M7_shop.svg", label: "M-7 SVG", note: "Shop method" },
    { href: "../", label: "Design page", note: "Marketing overview" },
    { href: "../../report/", label: "Engineering report", note: "Rev B full report" },
  ],
  tools: [
    "Festool track saw + MFT (Hongdui dogs / track hinge)",
    "Table saw + Festool TS LS 36 fence",
    "Woodpeckers Fence Guide V2",
    "Miter saw + Ryobi (rough crosscuts)",
    "Temple Tool rip + crosscut + flush trim saws",
    "Zenwu Y2 bench chisels + titanium hammer",
    "Stanley #5 + Bridge City bench plane",
    "Adrian Preda LW bench + shooting board",
    "Bridge City Universal V2 protractor",
    "Bridge City tenon tool + both kerf tools + Multi-Tool M1",
    "Incra 12″ rules + Kuratoga metal pencil",
    "Cordless drill + impact + Taylor countersink",
    "Clamps / bar clamps · paint kit",
  ],
  tolerances: [
    { item: "Layout", spec: "1/64″ on joinery faces · story-stick rail CL" },
    { item: "Nuki width", spec: "Measured rail thickness — sliding fit, no rattle" },
    { item: "Nuki height", spec: "7.25″ + 1/16″ seasonal ease only" },
    { item: "Foot tenon", spec: "2.5×4.5×12 · shoulders ±1/32″ · sleeve +¼″ clear" },
    { item: "Board plow", spec: "⅜″ deep × ⅞″ wide on TS (LS 36)" },
    { item: "Drawbore", spec: "⅛″ offset · ⌀⅜″ peg from MFT stop" },
    { item: "Plumb", spec: "≤⅛″ over 65″ post height" },
  ],
};
