/* WALTER DS-16 Build App — design data */
window.WALTER_DATA = {
  meta: {
    name: "WALTER",
    code: "DS-16",
    subtitle: "Dedicated drum thickness sander · 15.5″ capacity",
    revision: "A",
    capacity: 15.5,
    drumOd: 5,
    drumRpm: 1035,
    motorHp: 0.5,
    surfaceFpm: 1355,
    lineage: "ShopNotes 86 → Ron Walters → Rev A solid-table redesign",
  },
  modernizations: [
    "Solid laminated sliding table — conveyor abandoned (Walters failed tracking 3×)",
    "Adjustable idler-side flange bearing for parallelism / light taper",
    "½ HP dedicated motor with lockable gravity tension mount",
    "Precision-ground ¾″ shaft (was plain cold-rolled)",
    "1 mm disc relief every 4 MDF discs OR all-birch drum option",
    "Replaceable phenolic/Formica wear surface",
    "4″ dust port + removable hood doubles as drum guard",
  ],
  parts: [
    { id: "sides", group: "frame", label: "Side panels (2)", detail: '¾″ Baltic birch · 22″ × 30″', color: "#c4a574" },
    { id: "base", group: "frame", label: "Base deck", detail: "¾″ BB spanning clear width", color: "#a89070" },
    { id: "stretch", group: "frame", label: "Stretchers (3)", detail: '16.5″ × 4″ × ¾″ · mid carries elev nut', color: "#8a7355" },
    { id: "drum", group: "drum", label: "Sanding drum", detail: '⌀5″ × 15.75″ · 21×¾″ discs', color: "#b8a990" },
    { id: "shaft", group: "drum", label: "Shaft + bearings", detail: "¾″ TG&P · 2× flange bearings", color: "#8a9098" },
    { id: "table", group: "table", label: "Sliding table", detail: '16″ × 20″ × 1½″ laminate + wear face', color: "#d9dcde" },
    { id: "elev", group: "table", label: "Elevator", detail: "Acme/wood screw + dual star locks", color: "#6e7578" },
    { id: "motor", group: "drive", label: "Motor + pulleys", detail: "½ HP 1725 · 3″/5″ · 4L belt", color: "#5a6068" },
    { id: "hood", group: "hood", label: "Dust hood", detail: "Kerf-bent ¼″ ply · 4″ port", color: "#9aa8a0" },
  ],
  cutList: [
    { qty: 2, size: '22″ × 30″ × ¾″', stock: "Baltic birch", use: "Side panels" },
    { qty: 1, size: '~18″ × 22″ × ¾″', stock: "Baltic birch", use: "Base deck" },
    { qty: 3, size: '16.5″ × 4″ × ¾″', stock: "Baltic birch", use: "Stretchers" },
    { qty: 2, size: '16″ × 20″ × ¾″', stock: "BB / void-free ply", use: "Table laminate" },
    { qty: 1, size: '16″ × 20″', stock: "Phenolic / Formica", use: "Wear surface" },
    { qty: 21, size: '⌀5⅛″ × ¾″ → true ⌀5″', stock: "MDF + BB ends", use: "Drum discs" },
    { qty: 1, size: '22″ × ⌀¾″', stock: "Precision shaft", use: "Drum shaft" },
    { qty: 1, size: '~18″ × 12″ × ¼″', stock: "Pine / birch ply", use: "Hood blank" },
    { qty: 1, size: '12″ × 8″ × ¾″', stock: "Baltic birch", use: "Motor cradle" },
  ],
  hardware: [
    { item: "4-bolt flange bearings ¾″ sealed", qty: "2" },
    { item: '3″ motor pulley + 5″ drum pulley (4L)', qty: "1 set" },
    { item: "4L / A-section V-belt", qty: "1" },
    { item: "½ HP 1725 RPM TEFC motor 115 V", qty: "1" },
    { item: "Star knobs ⅜-16 + washers", qty: "4" },
    { item: "¾″ Acme or wood-thread elev kit", qty: "1" },
    { item: '4″ hook Velcro PSA', qty: "~5 ft" },
    { item: '3″ loop sandpaper rolls (80/120/180)', qty: "as needed" },
    { item: '⅛″ piano wire', qty: "12 in" },
    { item: '4″ dust adapter + blast gate', qty: "1" },
    { item: "Switch box + 15 ft cord", qty: "1" },
    { item: "Idler jack screws / shim kit", qty: "1" },
  ],
  assembly: [
    { id: "a1", phase: "frame", title: "Cut & dry-fit sides / base / stretchers", body: "Lay out flange-bearing centers, table slots, and motor cradle on both sides as a matched pair. Confirm clear span 16.5″." },
    { id: "a2", phase: "frame", title: "Assemble rigid box frame", body: "Glue + screw stretchers between Baltic birch sides. Square diagonals before the glue sets. Add base deck." },
    { id: "a3", phase: "drum", title: "Bore & stack drum discs", body: "Drill-press bore ⌀¾″ centers. Stack on shaft with piano-wire keys. Glue; leave 1 mm relief every 4 MDF discs." },
    { id: "a4", phase: "drum", title: "Mount bearings & true drum", body: "Drive-side bearing fixed. Idler on adjustable pad. True OD with abrasive on a sled against the table plane." },
    { id: "a5", phase: "drive", title: "Fit motor cradle, pulleys, belt", body: "Pivot motor on hardwood dowel; tension from motor weight. Lock so the running belt cannot pump the mount." },
    { id: "a6", phase: "table", title: "Laminate table + wear surface", body: "Glue two ¾″ panels face-to-face. Apply phenolic/Formica. Fit elevating screw and dual star-knob locks." },
    { id: "a7", phase: "hood", title: "Kerf-bend dust hood", body: "Kerf ¼″ ply, wet outer face, glue to form, fill kerfs with sawdust-glue. Add 4″ port." },
    { id: "a8", phase: "wrap", title: "Apply Velcro + spiral sandpaper", body: "Wrap hook Velcro tight. Cut spiral sandpaper from the first template; loop side mates to hooks." },
    { id: "a9", phase: "tune", title: "Parallelism & first passes", body: "Shim/jack idler bearing until feelers match both ends. Light passes only — not a planer." },
    { id: "a10", phase: "tune", title: "Safety check & dust test", body: "Verify hood lock, cord routing, switch, push-stick reach. Extraction before freehand use." },
  ],
  phases: [
    { id: "frame", label: "01 Frame" },
    { id: "drum", label: "02 Drum" },
    { id: "drive", label: "03 Drive" },
    { id: "table", label: "04 Table" },
    { id: "hood", label: "05 Hood" },
    { id: "wrap", label: "06 Wrap" },
    { id: "tune", label: "07 Tune" },
  ],
  safety: [
    "Hood ON is the primary guard — open only when stopped and unplugged.",
    "Hands never under the drum. Push sticks; ~12″ minimum stock length.",
    "Small parts ride a longer sled (kickback risk).",
    "Light passes only. Back off if the motor bogs.",
    "Eye, hearing, respirator when truing MDF.",
  ],
  gallery: [
    { src: "../plans/D1_general.svg", title: "D-1 General", kind: "plan" },
    { src: "../plans/D2_frame.svg", title: "D-2 Frame", kind: "plan" },
    { src: "../plans/D3_drum.svg", title: "D-3 Drum", kind: "plan" },
    { src: "../plans/D4_drive.svg", title: "D-4 Drive", kind: "plan" },
    { src: "../plans/D5_hood.svg", title: "D-5 Hood", kind: "plan" },
    { src: "../plans/D6_cutlist.svg", title: "D-6 Cut list", kind: "plan" },
  ],
  downloads: [
    { href: "../cad/walter_ds16.py", label: "walter_ds16.py", note: "Parametric engineering source" },
    { href: "../cad/walter_ds16.scad", label: "walter_ds16.scad", note: "OpenSCAD preview model" },
    { href: "../plans/D1_general.svg", label: "D-1 SVG", note: "General arrangement" },
    { href: "../plans/D6_cutlist.svg", label: "D-6 SVG", note: "Cut list & BOM" },
    { href: "../", label: "Design page", note: "Overview" },
  ],
  sources: [
    { label: "Ron Walters drum sander (woodgears)", href: "https://woodgears.ca/reader/walters/drum_sander.html" },
    { label: "Walters build walkthrough (YouTube)", href: "https://youtu.be/W-5Sj6kBVic" },
    { label: "Simon Heslop variant", href: "https://woodgears.ca/sander/drum.html" },
    { label: "Pat Hawley / Wandel free plans", href: "https://woodgears.ca/sander/plans/" },
  ],
  tools: [
    "Table saw / track saw",
    "Drill press (disc centers)",
    "Bandsaw or jigsaw (disc blanks)",
    "Router (optional slots)",
    "Clamps · squares · dial/feeler gauges",
    "Wood thread box or Acme tap",
    "Dust collector 4″",
  ],
};
