/* DS-18 shop drum sander — parametric data (inches). */
window.DS_DATA = {
  meta: {
    name: "DS-18",
    title: "Shop drum sander",
    drumLen: 18,
    drumOd: 6,
    shaftOd: 1,
    shaftLen: 24,
    cabW: 36,
    cabD: 22,
    cabH: 28,
    overallH: 42,
    tableW: 20,
    tableD: 22,
    tableTravel: 2.5,
    motorHp: 1.5,
    motorRpm: 1725,
    drumRpm: 860,
    dustPort: 4,
    weightLb: 185,
  },
  parts: [
    { id: "cabinet", name: "Plywood cabinet", note: "36×22×28 carcass, motor bay", color: "#c4a574" },
    { id: "uprights", name: "Bearing towers", note: "3/4″ plywood cheeks, left & right", color: "#b08958" },
    { id: "motor", name: "1.5 HP motor", note: "56-frame TEFC, 1725 RPM", color: "#2a2e33" },
    { id: "pulleyM", name: "Motor pulley", note: "2″ A-section, 1/2″ bore", color: "#8a9098" },
    { id: "pulleyD", name: "Drum pulley", note: "4″ A-section, 1″ bore", color: "#8a9098" },
    { id: "belt", name: "V-belt", note: "A-36, ~1:2 reduction", color: "#1a1a1a" },
    { id: "drum", name: "Sanding drum", note: "6″ OD × 18″, PSA wrap", color: "#d4a574" },
    { id: "shaft", name: "Drum shaft", note: "1″ × 24″ precision rod", color: "#c5cbcf" },
    { id: "bearings", name: "Pillow blocks", note: "Pair of 1″ bore PBs", color: "#5a6570" },
    { id: "table", name: "Infeed table", note: "20×22 × 3/4″, 2.5″ travel", color: "#d2b48c" },
    { id: "fence", name: "Edge fence", note: "3/4×3×20 hardwood", color: "#8b5a2b" },
    { id: "jacks", name: "Height jacks", note: "Four 1/2-13 screws + wheels", color: "#6a7a88" },
    { id: "hood", name: "Dust hood", note: "Wrap over drum, 4″ port", color: "#4a5560" },
    { id: "port", name: "Dust port", note: "4″ OD to collector", color: "#3d4650" },
    { id: "switch", name: "Magnetic switch", note: "Left cabinet, E-stop", color: "#c45a3a" },
  ],
  assembly: [
    { id: "a1", phase: "carcass", title: "Nest and cut plywood", body: "Lay out DS-2 on two 4×8 × 3/4″ Baltic birch sheets. Cut sides, front, back, bottom, motor shelf, table, aprons, and tower cheeks. Label every face." },
    { id: "a2", phase: "carcass", title: "Assemble the cabinet", body: "Glue and screw the 36×22×28 carcass. Bottom sits in a 3/8″ dado. Square diagonals before the glue sets. Leave the top open." },
    { id: "a3", phase: "carcass", title: "Motor shelf and wiring chase", body: "Install the 14″-deep shelf 8″ off the bottom on the left. Bore a 1.5″ belt slot in the left wall and a 7/8″ strain-relief hole for the cord." },
    { id: "a4", phase: "drum", title: "Stand the bearing towers", body: "Bolt 6×14 cheeks to the cabinet top, 19″ apart inside. Confirm they are coplanar — a twisted tower will kill the drum." },
    { id: "a5", phase: "drum", title: "Align pillow blocks", body: "Set both 1″ pillow blocks on the towers. Stretch a taut line or use a long 1″ dummy rod. Shim until the shaft spins by hand with no bind." },
    { id: "a6", phase: "drum", title: "Build the drum on the shaft", body: "Press or set-screw the hubs into the 6″ tube. Slide the 24″ shaft through, lock collars outboard of each hub, wrap 18″ PSA paper later." },
    { id: "a7", phase: "drum", title: "Hang the drum", body: "Drop the shaft into the pillow blocks. End play ≤ 0.010″. Fit the 4″ pulley on the left stub. Spin: it must run true within 0.015″ TIR." },
    { id: "a8", phase: "drum", title: "Drive and belt", body: "Bolt the 1.5 HP motor to the shelf. Fit the 2″ pulley. A-36 belt through the wall slot. Tension until the belt deflects ~1/2″ at mid-span." },
    { id: "a9", phase: "table", title: "Table and four jacks", body: "Build the 20×22 table with 3.5″ aprons. Press T-nuts at the four corners. Thread 1/2-13 jack screws from below with handwheels. Travel 2.5″." },
    { id: "a10", phase: "table", title: "Fence and stops", body: "Screw the 3×20 fence to the back edge of the table, 90° to the drum axis. Add a 1/8″ UHMW wear strip on the infeed lip." },
    { id: "a11", phase: "finish", title: "Dust hood and 4″ port", body: "Wrap the hood over the drum leaving ~3/8″ clearance. Port exits the back at 4″ OD. Seal joints. Hook a collector before any test run." },
    { id: "a12", phase: "finish", title: "Wire, wrap, true, test", body: "Magnetic switch on the left, E-stop in reach. Wrap 80-grit PSA. Jog the drum. Dress high spots with a sanding block. First pass: scrap pine, 1/64″ take." },
  ],
  cutlist: [
    { id: "c1", qty: 2, material: "3/4″ birch", size: "22 × 28", part: "Cabinet sides", sheet: "A" },
    { id: "c2", qty: 1, material: "3/4″ birch", size: "34½ × 28", part: "Cabinet front", sheet: "A" },
    { id: "c3", qty: 1, material: "3/4″ birch", size: "34½ × 28", part: "Cabinet back", sheet: "B" },
    { id: "c4", qty: 1, material: "3/4″ birch", size: "34½ × 20½", part: "Cabinet bottom", sheet: "B" },
    { id: "c5", qty: 1, material: "3/4″ birch", size: "34½ × 14", part: "Motor shelf", sheet: "B" },
    { id: "c6", qty: 2, material: "3/4″ birch", size: "6 × 14", part: "Bearing towers", sheet: "A" },
    { id: "c7", qty: 1, material: "3/4″ birch", size: "20 × 22", part: "Table top", sheet: "B" },
    { id: "c8", qty: 2, material: "3/4″ birch", size: "3½ × 22", part: "Table aprons (sides)", sheet: "A" },
    { id: "c9", qty: 2, material: "3/4″ birch", size: "3½ × 18½", part: "Table aprons (ends)", sheet: "A" },
    { id: "c10", qty: 2, material: "3/4″ birch", size: "12 × 8", part: "Hood cheeks", sheet: "A" },
    { id: "c11", qty: 1, material: "26 ga steel", size: "20 × 12", part: "Hood wrap", sheet: "—" },
    { id: "c12", qty: 1, material: "hardwood", size: "¾ × 3 × 20", part: "Fence", sheet: "offcut" },
    { id: "c13", qty: 1, material: "UHMW", size: "⅛ × ¾ × 20", part: "Infeed wear strip", sheet: "—" },
  ],
  shopping: [
    { id: "s1", qty: "2", item: "4×8 × 3/4″ Baltic birch", use: "Carcass, table, towers", est: 160 },
    { id: "s2", qty: "1", item: "1.5 HP 1725 RPM TEFC motor, 56 frame", use: "Drum drive", est: 180 },
    { id: "s3", qty: "1 pr", item: "1″ bore pillow-block bearings", use: "Drum journals", est: 45 },
    { id: "s4", qty: "1", item: "1″ × 24″ precision shaft, 1045", use: "Drum axle", est: 35 },
    { id: "s5", qty: "1", item: "6″ OD × 18″ aluminum or steel tube + hubs", use: "Sanding drum", est: 55 },
    { id: "s6", qty: "1", item: "2″ A-section pulley, 1/2″ bore", use: "Motor", est: 14 },
    { id: "s7", qty: "1", item: "4″ A-section pulley, 1″ bore", use: "Drum", est: 18 },
    { id: "s8", qty: "1", item: "A-36 V-belt", use: "Reduction drive", est: 12 },
    { id: "s9", qty: "4", item: "1/2-13 × 8″ jack screw + handwheel", use: "Table height", est: 48 },
    { id: "s10", qty: "4", item: "1/2-13 T-nuts", use: "Table corners", est: 8 },
    { id: "s11", qty: "1", item: "4″ dust port flange", use: "Collector hookup", est: 12 },
    { id: "s12", qty: "1", item: "Magnetic motor starter + E-stop", use: "Power", est: 55 },
    { id: "s13", qty: "1", item: "18″ PSA sandpaper roll (80/120/180)", use: "Abrasive", est: 40 },
    { id: "s14", qty: "4", item: "3″ locking casters", use: "Mobility", est: 32 },
    { id: "s15", qty: "1 box", item: "#8 × 1-1/4″ pocket / cabinet screws", use: "Carcass", est: 12 },
    { id: "s16", qty: "1 kit", item: "1/4-20 bolts, lock collars, set screws", use: "Drum / pulleys", est: 18 },
    { id: "s17", qty: "1", item: "Wood glue + finish (wipe-on poly)", use: "Cabinet", est: 22 },
  ],
  tools: [
    "Table saw or track saw",
    "Drill press (bearing towers)",
    "Dial indicator or truing stick",
    "Socket set + hex keys",
    "Dust collector ≥ 350 CFM",
    "Multimeter (motor wiring)",
  ],
  plans: [
    { id: "DS-1", href: "plans/DS1_general.svg", title: "General arrangement", note: "Front + side elevations" },
    { id: "DS-2", href: "plans/DS2_plywood.svg", title: "Plywood nesting", note: "Two 4×8 sheets" },
    { id: "DS-3", href: "plans/DS3_drum.svg", title: "Drum, shaft, bearings", note: "Journals & TIR" },
    { id: "DS-4", href: "plans/DS4_table.svg", title: "Table & jacks", note: "2.5″ travel" },
    { id: "DS-5", href: "plans/DS5_drive.svg", title: "Drive & dust", note: "Pulleys, belt, hood" },
    { id: "DS-6", href: "plans/DS6_cutlist.svg", title: "Cut list & hardware", note: "Shop copy" },
  ],
  files: [
    { href: "plans/DS1_general.svg", label: "DS-1 SVG", note: "General arrangement" },
    { href: "plans/DS2_plywood.svg", label: "DS-2 SVG", note: "Plywood nesting" },
    { href: "plans/DS3_drum.svg", label: "DS-3 SVG", note: "Drum & shaft" },
    { href: "plans/DS4_table.svg", label: "DS-4 SVG", note: "Table & jacks" },
    { href: "plans/DS5_drive.svg", label: "DS-5 SVG", note: "Drive & dust" },
    { href: "plans/DS6_cutlist.svg", label: "DS-6 SVG", note: "Cut list" },
    { href: "../cad/drum_sander.scad", label: "drum_sander.scad", note: "OpenSCAD parametric" },
    { href: "data.js", label: "data.js", note: "Dimensions & BOMs" },
  ],
  safety: [
    "Never reach under a spinning drum. Stop, wait, then adjust jacks.",
    "Dust collection on before any cut. Fine sanding dust is combustible.",
    "Wrap PSA with the drum unplugged. Overlap ~1/4″, no wrinkles.",
    "Max take per pass: 1/32″ hardwood, 1/16″ pine. Listen for bogging.",
    "Magnetic switch so a power blip does not restart the drum.",
  ],
};
