/* WALTER DS-16 Build App — design data (Rev B) */
window.WALTER_DATA = {
  meta: {
    name: "WALTER",
    code: "DS-16",
    subtitle: "Dedicated drum thickness sander · 15.5″ · geometry Rev B",
    revision: "B",
    capacity: 15.5,
    drumOd: 5,
    drumRpm: 1035,
    motorHp: 0.5,
    surfaceFpm: 1355,
    parallelTol: 0.003,
    lineage: "ShopNotes 86 → Ron Walters → Rev A solid table → Rev B geometry",
  },
  modernizations: [
    "Dual ½-10 Acme screws, chain-coupled — table stays coplanar while rising",
    "Left screw uncouples for taper; dog stop returns to parallel home",
    "UHMW ways — table cannot rack under feed load",
    "Stack-drill sides as a pair; floating idler bearing (no banana shaft)",
    "Torsion-box table + phenolic / tooling-plate wear face",
    "Spring hold-down rollers — kills snipe and chatter",
    "True, wrap, then re-clock A/B to ±0.003″ (paper-on is the real spec)",
    "Optional ⅛″ slow oscillation to erase spiral tracks",
  ],
  parts: [
    { id: "sides", group: "frame", label: "Side panels (2)", detail: "¾″ BB · stack-drilled as a pair", color: "#c4a574" },
    { id: "ways", group: "frame", label: "UHMW ways", detail: "Inner-face vertical reference · no rack", color: "#d9dcde" },
    { id: "base", group: "frame", label: "Base + stretchers", detail: "¾″ BB box · diagonals square", color: "#a89070" },
    { id: "drum", group: "drum", label: "Sanding drum", detail: "⌀5″ · pack-bored · balanced ends", color: "#b8a990" },
    { id: "shaft", group: "drum", label: "Shaft + bearings", detail: "Fixed drive · floating idler", color: "#8a9098" },
    { id: "table", group: "table", label: "Torsion-box table", detail: "Skins + ribs + phenolic/MIC-6", color: "#cfd3d5" },
    { id: "elev", group: "table", label: "Dual Acme lift", detail: "Chain couple · left clutch · home dog", color: "#6e7578" },
    { id: "rollers", group: "table", label: "Hold-down rollers", detail: "Infeed/outfeed · 0.030″ below drum", color: "#5a6068" },
    { id: "motor", group: "drive", label: "Motor + pulleys", detail: "½ HP · coplanar 3″/5″ · locked cradle", color: "#4a5058" },
    { id: "hood", group: "hood", label: "Dust hood", detail: "Kerf-bent · 4″ port · osc clearance", color: "#9aa8a0" },
  ],
  cutList: [
    { qty: 2, size: '22″ × 30″ × ¾″', sizeMm: "559 × 762 × 19 mm", stock: "Baltic birch", use: "Side panels — stack-drill" },
    { qty: 1, size: '~18″ × 22″ × ¾″', sizeMm: "457 × 559 × 19 mm", stock: "Baltic birch", use: "Base deck" },
    { qty: 3, size: '16.5″ × 4″ × ¾″', sizeMm: "419 × 102 × 19 mm", stock: "Baltic birch", use: "Stretchers" },
    { qty: 2, size: '16″ × 22″ × ¾″', sizeMm: "406 × 559 × 19 mm", stock: "BB skins", use: "Table torsion-box" },
    { qty: 1, size: "½″ grid offcuts", sizeMm: "12 mm grid", stock: "BB / MDF", use: "Ribs @ 4″ o.c." },
    { qty: 1, size: '16″ × 22″ × ½″', sizeMm: "406 × 559 × 12 mm", stock: "Phenolic / MIC-6", use: "Wear face" },
    { qty: 2, size: '¾″ × ¾″ × 22″', sizeMm: "19 × 19 × 559 mm", stock: "UHMW", use: "Table ways" },
    { qty: 21, size: '⌀5⅛″ × ¾″ → true ⌀5″', sizeMm: "⌀130 → ⌀127 × 19 mm", stock: "MDF + BB ends", use: "Drum discs — pack-bore" },
    { qty: 1, size: '22.5″ × ⌀¾″', sizeMm: "572 × ⌀19 mm", stock: "Precision shaft", use: "Drum shaft" },
    { qty: 1, size: '~18″ × 12″ × ¼″', sizeMm: "~457 × 305 × 6 mm", stock: "Pine / birch ply", use: "Hood blank" },
    { qty: 1, size: '16″ × 8″ × ¾″', sizeMm: "406 × 203 × 19 mm", stock: "MDF / BB", use: "Truing sled" },
    { qty: 2, size: '18″ × 3″ × ¾″', sizeMm: "457 × 76 × 19 mm", stock: "Hardwood / angle", use: "Roller yokes" },
  ],
  hardware: [
    { item: "4-bolt flange ¾″ — FIXED (drive)", qty: "1" },
    { item: "4-bolt flange ¾″ — FLOATING (idler)", qty: "1" },
    { item: '3″ + 5″ 4L pulleys + belt', qty: "1 set" },
    { item: "½ HP 1725 RPM TEFC 115 V", qty: "1" },
    { item: "½-10 Acme 12″ + bronze nut", qty: "2" },
    { item: "#25 sprockets + chain + left clutch/dog", qty: "1 kit" },
    { item: '⌀1.25″ rubber rollers ~15.75″ + ⅜″ axles', qty: "2" },
    { item: "Compression springs + shoulder bolts", qty: "4" },
    { item: "Dial indicator 0.001″ + mag base", qty: "1" },
    { item: "Velcro + 80/120/180/220 loop paper", qty: "as needed" },
    { item: "Optional 60–90 RPM gearmotor oscillator", qty: "1 kit" },
  ],
  assembly: [
    { id: "a1", phase: "frame", title: "Template & stack-drill sides", body: "Clamp both side panels face-to-face. Drill bearing CLs, way holes, and indicator pad as one stack." },
    { id: "a2", phase: "frame", title: "Assemble box + UHMW ways", body: "Glue + screw stretchers. Square diagonals. Bond UHMW ways — they are the table’s vertical reference." },
    { id: "a3", phase: "drum", title: "Pack-bore discs & laminate drum", body: "Stack all discs in the bore jig; ream ⌀¾″ as a pack. Key, glue, 1 mm MDF relief, static-balance ends." },
    { id: "a4", phase: "drum", title: "Fixed drive bearing, floating idler", body: "Lock drive flange. Idler on axial-float pad so the shaft cannot banana." },
    { id: "a5", phase: "drive", title: "Motor cradle, coplanar pulleys, lock", body: "Straightedge across pulley faces. Gravity tension, then lock the cradle." },
    { id: "a6", phase: "table", title: "Torsion-box table + wear face", body: "Skins + 4″ rib grid, continuous glue. Bond phenolic/MIC-6. Diagonals ≤ 0.004″." },
    { id: "a7", phase: "table", title: "Dual Acme lift + chain couple", body: "Bronze nuts in table. Chain both screws. Fit left clutch and parallel-home dog." },
    { id: "a8", phase: "table", title: "Hold-down roller yokes", body: "Infeed and outfeed. Set 0.030″ below drum OD (paper on). Too much spring = snipe." },
    { id: "a9", phase: "hood", title: "Kerf-bend dust hood", body: "Kerf, wet, glue, fill. 4″ port. Clear oscillator stroke if fitted." },
    { id: "a10", phase: "wrap", title: "True drum on full-width sled", body: "Abrasive face-up, sled rides the ways. TIR ≤ 0.002″, then Velcro + spiral paper." },
    { id: "a11", phase: "tune", title: "Indicator clock A/B — parallel home", body: "Paper on. |A−B| ≤ 0.003″. Lock home dog. Record the reading." },
    { id: "a12", phase: "tune", title: "Test panel + pass schedule", body: "80 / 120 / 180. Caliper four corners. Finish at 0.001″. Optional oscillator last." },
  ],
  phases: [
    { id: "frame", label: "01 Frame" },
    { id: "drum", label: "02 Drum" },
    { id: "drive", label: "03 Drive" },
    { id: "table", label: "04 Table" },
    { id: "hood", label: "05 Hood" },
    { id: "wrap", label: "06 Wrap" },
    { id: "tune", label: "07 Tune" },
  ],
  quality: [
    { check: "Table flatness", spec: "≤ 0.004″ on both diagonals", tool: "Straightedge + feelers" },
    { check: "Drum TIR (paper off)", spec: "≤ 0.002″ TIR", tool: "Dial indicator mid-span" },
    { check: "Drum ∥ table (paper on)", spec: "|A−B| ≤ 0.003″ over 15.5″", tool: "Indicator at drive and idler" },
    { check: "Way coplanar", spec: "No twist; slides without bind", tool: "Winding sticks" },
    { check: "Pulley coplanar", spec: "Faces flush; belt centered", tool: "Straightedge on pulleys" },
    { check: "Hold-down set", spec: "Rollers 0.030″ below drum OD", tool: "Feelers, paper on" },
    { check: "Thickness scatter", spec: "≤ 0.003″ on test panel", tool: "Caliper 4 corners" },
  ],
  calibration: [
    { id: "c1", title: "Disconnect power", body: "Unplug. Hood off. Paper off for TIR; paper on for A/B." },
    { id: "c2", title: "Seat the table in the ways", body: "Full travel. No bind, no rock. Winding sticks — no twist." },
    { id: "c3", title: "Drum TIR", body: "Indicator mid-span. If > 0.002″, re-true on the sled before wrapping." },
    { id: "c4", title: "Wrap & re-clock", body: "Velcro then spiral paper. Paper is not uniform — A/B will change." },
    { id: "c5", title: "A/B parallel", body: "Uncouple left Acme; 1/40 turn ≈ 0.0025″. Recouple. Set home dog." },
    { id: "c6", title: "Hold-down height", body: "0.030″ below drum. Leading snipe → ease outfeed; trailing → ease infeed." },
    { id: "c7", title: "Witness board", body: "6″ × 16″ maple, one 80-grit pass. Ridge = B high/low. Log corners." },
    { id: "c8", title: "Taper mode (optional)", body: "Uncouple left, drop B, sand, return to home dog — do not reinvent parallel." },
  ],
  passes: [
    { grit: "80", depth: "0.008″", use: "Flatten / mill marks / glue" },
    { grit: "120", depth: "0.004″", use: "Thickness to +0.008″ of final" },
    { grit: "180", depth: "0.001″", use: "Finish pass; optional 90° cross" },
    { grit: "220", depth: "0.001″", use: "Veneer / figured maple" },
  ],
  safety: [
    "Hood ON is the primary guard — open only when stopped and unplugged.",
    "Hold-downs on. Hands never under the drum. ~12″ min length or a sled.",
    "Small parts ride a longer sled (kickback risk).",
    "Light passes only. Back off if the motor bogs.",
    "Eye, hearing, respirator when truing MDF.",
  ],
  gallery: [
    { src: "../plans/D1_general.svg", title: "D-1 General", kind: "plan" },
    { src: "../plans/D2_frame.svg", title: "D-2 Frame", kind: "plan" },
    { src: "../plans/D3_drum.svg", title: "D-3 Drum", kind: "plan" },
    { src: "../plans/D4_drive.svg", title: "D-4 Drive", kind: "plan" },
    { src: "../plans/D5_hood.svg", title: "D-5 Hood", kind: "plan" },
    { src: "../plans/D6_cutlist.svg", title: "D-6 Cut list", kind: "plan" },
    { src: "../plans/D7_geometry.svg", title: "D-7 Geometry", kind: "plan" },
    { src: "../plans/D8_holddowns.svg", title: "D-8 Hold-downs", kind: "plan" },
    { src: "../plans/D9_model.svg", title: "D-9 3D views", kind: "plan" },
    { src: "../plans/D10_lumberyard.svg", title: "D-10 Lumberyard", kind: "plan" },
    { src: "../renders/iso_assembled.svg", title: "Iso assembled", kind: "render" },
    { src: "../renders/iso_exploded.svg", title: "Iso exploded", kind: "render" },
    { src: "../renders/ortho_front.svg", title: "Front solid", kind: "render" },
    { src: "../renders/ortho_side.svg", title: "Drive side", kind: "render" },
  ],
  lumberyard: [
    { where: "Plywood", item: "¾″ Baltic birch (18 mm Euro BB OK)", qty: "2 × 5′×5′", use: "Frame + table skins" },
    { where: "MDF", item: "¾″ MDF 24″ × 48″", qty: "1", use: "21 discs + jig" },
    { where: "Plywood", item: "¼″ birch/pine ply 24″ × 24″", qty: "1", use: "Hood blank" },
    { where: "Plastics", item: "½″ phenolic or ⅜″ MIC-6 16″ × 22″", qty: "1", use: "Wear face" },
    { where: "Plastics", item: "UHMW ¾″ × ¾″ × 48″", qty: "1", use: "Ways" },
    { where: "Abrasives", item: "4″ hook Velcro + 3″ loop 80/120/180/220", qty: "kit", use: "Wrap after truing" },
  ],
  fasteners: [
    { qty: "~100", item: "#8 × 1¼″ cabinet screws", use: "Box, skins, hood" },
    { qty: "~50", item: "#8 × 2″ screws", use: "Sides into stretchers" },
    { qty: "8", item: "¼-20 T-nuts + bolts", use: "Motor cradle" },
    { qty: "8", item: "5/16-18 × 1″ + nylock", use: "Flange bearings" },
    { qty: "6", item: "⅜-16 star knobs", use: "Way locks / yokes" },
    { qty: "4", item: "Light compression springs", use: "Hold-downs" },
    { qty: "2", item: "⅜″ × 17″ rod", use: "Roller axles" },
    { qty: "12″", item: "⅛″ piano wire", use: "Disc keys" },
  ],
  downloads: [
    { href: "../pack/WALTER-DS16-RevB.zip", label: "Shop pack (ZIP)", note: "Plans, BOM, CAD — Save to Files", download: "WALTER-DS16-RevB.zip", share: true, primary: true },
    { href: "../pocket/", label: "Pocket field card", note: "Phone shop floor · Add to Home Screen" },
    { href: "../pack/BOM.csv", label: "BOM.csv", note: "Cut list inch + mm", download: "WALTER-DS16-BOM.csv" },
    { href: "../pack/fasteners.csv", label: "fasteners.csv", note: "Hardware-aisle list", download: "WALTER-DS16-fasteners.csv" },
    { href: "../pack/lumberyard.csv", label: "lumberyard.csv", note: "Store-trip sheet goods", download: "WALTER-DS16-lumberyard.csv" },
    { href: "../cad/walter_ds16.py", label: "walter_ds16.py", note: "Parametric engineering source", download: "walter_ds16.py" },
    { href: "../cad/walter_ds16.scad", label: "walter_ds16.scad", note: "OpenSCAD solid model", download: "walter_ds16.scad" },
    { href: "../model/", label: "3D viewer", note: "Orbit / explode" },
    { href: "../plans/D10_lumberyard.svg", label: "D-10 SVG", note: "Nesting + store card", download: "D10_lumberyard.svg" },
    { href: "../plans/D9_model.svg", label: "D-9 SVG", note: "Isometric solids", download: "D9_model.svg" },
    { href: "../plans/D1_general.svg", label: "D-1 SVG", note: "General arrangement", download: "D1_general.svg" },
    { href: "../plans/D7_geometry.svg", label: "D-7 SVG", note: "Geometry & calibration", download: "D7_geometry.svg" },
    { href: "../", label: "Design page", note: "Overview" },
  ],
  sources: [
    { label: "Ron Walters drum sander (woodgears)", href: "https://woodgears.ca/reader/walters/drum_sander.html" },
    { label: "Walters build walkthrough (YouTube)", href: "https://youtu.be/W-5Sj6kBVic" },
    { label: "Simon Heslop variant", href: "https://woodgears.ca/sander/drum.html" },
    { label: "Pat Hawley / Wandel free plans", href: "https://woodgears.ca/sander/plans/" },
  ],
  tools: [
    "Table saw / track saw",
    "Drill press + pack-bore jig",
    "Dial indicator 0.001″ + mag base",
    "Feelers / winding sticks / calipers",
    "Clamps · squares",
    "Dust collector 4″",
  ],
};
