// SHINOBI//82 KAGE — parametric CAD source (mm)
// Proposed geometry for conversation. Not a released manufacturing package.
// Companion meshes are generated by build_parts.py from parameters.json.

frame_length = 94;
frame_height = 16.2;
frame_ridge = 4.6;
frame_rail = 1.7;
pommel_hole = 4.4;

mizu_blade = 82;
mizu_tang = 28;
mizu_heel_h = 15.2;
mizu_tip_h = 6.2;
mizu_heel_t = 1.55;
mizu_tip_t = 0.60;

kumiko_blade = 42;
kumiko_bevel = 15;

nata_blade = 60;
nata_bevel = 24;

saya_length = 92;
spike_point = 34;
togi_length = 52;
togi_width = 18;
togi_thick = 2.8;

module rail(size, pos) { translate(pos) cube(size, center=true); }

module frame() {
    rail([frame_length-8, frame_rail, frame_ridge], [frame_length/2-2, frame_height/2-frame_rail/2, 0]);
    rail([frame_length-18, frame_rail, frame_ridge*0.78], [frame_length/2-6, -frame_height/2+frame_rail/2, 0]);
    rail([3.6, frame_height-2.2, frame_ridge*0.7], [18, 0, 0]);
    rail([3.6, frame_height-3.4, frame_ridge*0.7], [40, 0.4, 0]);
    rail([3.6, frame_height-2.8, frame_ridge*0.7], [62, -0.2, 0]);
    difference() {
        translate([frame_length+2, 0, 0]) cylinder(h=frame_ridge, r=frame_height/2.15, center=true, $fn=32);
        translate([frame_length+2, 0, 0]) cylinder(h=frame_ridge+2, r=pommel_hole/2, center=true, $fn=28);
    }
}

module togi() {
    difference() {
        cube([togi_length, togi_width, togi_thick], center=true);
        translate([togi_length/2-6, 4.2, 0]) cylinder(h=togi_thick+2, r=1.6, center=true, $fn=24);
        translate([togi_length/2-6, -4.2, 0]) cylinder(h=togi_thick+2, r=1.6, center=true, $fn=24);
    }
}

module spike() {
    rotate([0, -90, 0]) cylinder(h=spike_point, r1=1.7, r2=0.18, $fn=28);
}

frame();
translate([0, 40, 0]) togi();
translate([0, 70, 0]) spike();
